on:
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        description: Enable Debugging

  push:
    branches: ["**"]

    paths-ignore:
      - "**/*.md"

  pull_request:
    branches: ["**"]

name: Test

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        config: ["Release", "Debug"]
        container: ["archlinux", "fedora:40"]

    runs-on: ubuntu-latest
    container: ${{ matrix.container }}

    name: 🧪 Test on ${{ matrix.container }} (⚙️ ${{ matrix.config }})

    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v4

      - name: 🧰 Install Dependencies
        if: ${{ matrix.container == 'archlinux' }}
        run: "pacman --noconfirm -Syu base-devel cmake gcc git make pipewire pipewire-pulse"

      - name: 🧰 Install Dependencies
        if: ${{ matrix.container == 'fedora:40' }}
        run: "dnf install -y pipewire-devel make automake git gcc gcc-c++ kernel-devel cmake libasan"

      - name: 🐛 Debug Workflow
        if: ${{ github.event.inputs.debug == 'true' }}
        uses: mxschmitt/action-tmate@v3
        with:
          install-dependencies: false
          limit-access-to-actor: true

      - name: 🔨 Compile
        run: "mkdir build && cd build && cmake .. -Drohrkabel_examples=ON -Drohrkabel_sanitizer=ON && cmake --build . --config ${{ matrix.config }}"
