on:
  workflow_dispatch:
  push:
    branches: ["**"]
    paths-ignore:
      - "**/*.md"
      - "**/*.yml"
  pull_request:
    branches: ["**"]

name: Test on Fedora-Linux
jobs:
  test-fedora-36-release:
    runs-on: ubuntu-latest
    container: fedora:36
    strategy:
      fail-fast: false
      matrix:
        language: ["cpp"]

    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0

      - name: Install build dependencies
        run: "dnf install -y pipewire-devel make automake git gcc gcc-c++ kernel-devel cmake"

      - name: Compile
        run: "mkdir build && cd build && cmake .. -Drohrkabel_examples=ON && cmake --build . --config Release"

  test-fedora-36-debug:
    runs-on: ubuntu-latest
    container: fedora:36
    strategy:
      fail-fast: false
      matrix:
        language: ["cpp"]

    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0

      - name: Install build dependencies
        run: "dnf install -y pipewire-devel make automake git gcc gcc-c++ kernel-devel cmake"

      - name: Compile
        run: "mkdir build && cd build && cmake .. -Drohrkabel_examples=ON && cmake --build . --config Debug"
